name: Daily Weather Fetcher

on:
  schedule:
    - cron: '0 0,12 * * *' # Chạy vào 0:00 và 12:00 UTC mỗi ngày
  workflow_dispatch: # Cho phép bấm chạy thủ công trên GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pipeline
        env:
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python src/run_pipeline.py

      - name: Lữu trữ file Raw và Clean (Upload Artifacts)
        uses: actions/upload-artifact@v4
        with:
            name: weather-data-${{ github.run_id }} # Tên thư mục tải về
            path: |
              src/data/raw/*.csv
              src/data/clean/*.csv
            retention-days: 30 # (Tùy chọn) Số ngày GitHub sẽ lưu trữ file này trước khi tự động xóa. Bạn có thể chỉnh sửa số này.